```{r}
###
# Loading libs
###
library(tidyverse)
library(janitor)
```

```{r}
###
# Loading in data
###
porter_spending <- read_csv("data/porter_spending.csv")
schiff_spending <- read_csv("data/schiff_spending.csv")

porter_spending <- porter_spending %>%
  select(committee_name, entity_type, recipient_name, recipient_state, disbursement_description, disbursement_date, disbursement_amount, candidate_office, candidate_name, candidate_office_state)
schiff_spending <- schiff_spending %>%
  select(committee_name, entity_type, recipient_name, recipient_state, disbursement_description, disbursement_date, disbursement_amount, candidate_office, candidate_name, candidate_office_state)

###
# What type of disbursements are there? Need to narrow down to PAC and candidate contribs
###
porter_spending %>%
  group_by(disbursement_description) %>%
  count()
schiff_spending %>%
  group_by(disbursement_description) %>%
  count()

porter_contribs <- porter_spending %>%
  filter(disbursement_description == "CONTRIBUTION TO FEDERAL COMMITTEE" | disbursement_description == "CONTRIBUTION TO FEDERAL COMMITTTEE" | disbursement_description == "CONTRIBUTION TO NON-FEDERAL COMMITTEE")

schiff_contribs <- schiff_spending %>%
  filter(disbursement_description == "CIVIC CONTRIBUTION" | disbursement_description == "CIVIC DONATION" | disbursement_description == "CONTRIBUTION" | disbursement_description == "FEDERAL CONTRIBUTION" | disbursement_description == "FEDERAL CONTRIBUTION - 30114(A)(4) TRANSFER" | disbursement_description == "MONETARY CONTRIBUTION" | disbursement_description == "NON-FEDERAL CONTRIBUTION" | disbursement_description == "NON-FEDERAL CONTRIBUTION.")

###
# Contributions to federal candidates
###
schiff_contribs_fed_cands <- schiff_contribs %>%
  filter(disbursement_description == "FEDERAL CONTRIBUTION") %>%
  filter(entity_type == "CCM")

schiff_top_fed_cands <- schiff_contribs_fed_cands %>%
  group_by(recipient_name, recipient_state) %>%
  summarise(total = sum(disbursement_amount)) %>%
  arrange(desc(total))

porter_contribs_fed_cands <- porter_contribs %>%
  filter(disbursement_description == "CONTRIBUTION TO FEDERAL COMMITTEE" | disbursement_description == "CONTRIBUTION TO FEDERAL COMMITTTEE") %>%
  filter(entity_type == "CCM")

porter_top_fed_cands <- porter_contribs_fed_cands %>%
  group_by(recipient_name, recipient_state) %>%
  summarise(total = sum(disbursement_amount)) %>%
  arrange(desc(total))

###
# PAC contribs
###
schiff_pac_contribs <- schiff_contribs %>%
  filter(entity_type == "PAC")

schiff_top_pacs <- schiff_pac_contribs %>%
  group_by(recipient_name, recipient_state) %>%
  summarise(total = sum(disbursement_amount)) %>%
  arrange(desc(total))

porter_pac_contribs <- porter_contribs %>%
  filter(entity_type == "PAC")

porter_top_pacs <- porter_pac_contribs %>%
  group_by(recipient_name, recipient_state) %>%
  summarise(total = sum(disbursement_amount)) %>%
  arrange(desc(total))

###
# Everything else that isn't a federal committee or candidate
###
schiff_everything_else <- schiff_contribs %>%
  filter(disbursement_description != "FEDERAL CONTRIBUTION") %>%
  filter(disbursement_description != "FEDERAL CONTRIBUTION - 30114(A)(4) TRANSFER") %>%
  filter(entity_type != "PAC")

schiff_top_everything_else <- schiff_everything_else %>%
  group_by(recipient_name, recipient_state) %>%
  summarise(total = sum(disbursement_amount)) %>%
  arrange(desc(total))

porter_everything_else <- porter_contribs %>%
  filter(disbursement_description != "CONTRIBUTION TO FEDERAL COMMITTTEE") %>%
  filter(disbursement_description != "CONTRIBUTION TO FEDERAL COMMITTEE")

###
# Some general exploration of these datasets
###
schiff_total_to_fed <- paste(schiff_contribs_fed_cands %>%
  summarise(total = sum(disbursement_amount)))

porter_total_to_fed <- paste(porter_contribs_fed_cands %>%
                               summarise(total = sum(disbursement_amount)))

schiff_total_to_pacs <- paste(schiff_pac_contribs %>%
  summarise(total = sum(disbursement_amount)))

porter_total_to_pacs <- paste(porter_pac_contribs %>%
  summarise(total = sum(disbursement_amount)))

schiff_total_everything_else <- paste(schiff_everything_else %>%
  summarise(total = sum(disbursement_amount)))

porter_total_everything_else <- paste(porter_everything_else %>%
  summarise(total = sum(disbursement_amount)))


```

```{r}
###
# Loading in fundraising data
###

porter_raising <- read_csv("data/porter_raising.csv")
schiff_raising <- read_csv("data/schiff_raising.csv")

porter_raising <- porter_raising %>%
  clean_names() %>%
  select(committee_name_2, entity_type, contributor_name, contributor_city, contributor_state, contribution_receipt_date, contribution_receipt_amount)

schiff_raising <- schiff_raising %>%
  clean_names() %>%
  select(committee_name_2, entity_type, contributor_name, contributor_city, contributor_state, contribution_receipt_date, contribution_receipt_amount)

###
# some topline exploration of this data
###

porter_total_raised <- paste(porter_raising %>%
                               summarise(total = sum(contribution_receipt_amount)))

schiff_total_raised <-paste(schiff_raising %>%
                              summarise(total = sum(contribution_receipt_amount)))
```



